### ISSUE TITLE
Nested repeat variables with same name handled improperly

### ISSUE THREAD

**Issue by d-maurer** [malthe/chameleon#311] opened 2020-05-27 08:32 UTC
Playing around with a proper error representation for the `RepeatDict`, I got the impression that nested repeat variables using the same name could be improperly handled.

The following script demonstrates that this is really the case:
```
>>> from chameleon.zpt.template import PageTemplate
>>> t = PageTemplate("""\
... <div tal:repeat="i (1, 2, 3)">
...   <span tal:content="'%s(%s)' % (i, repeat['i'].index)" />: <span tal:repeat="i (1, 2, 3)" tal:content="i" /></div>
... """)
>>> print (t())
<div>
  <span>1(0)</span>: <span>1</span>
  <span>2</span>
  <span>3</span></div>
<div>
  <span>2(2)</span>: <span>1</span>
  <span>2</span>
  <span>3</span></div>
<div>
  <span>3(2)</span>: <span>1</span>
  <span>2</span>
  <span>3</span></div>
```
As you see, the inner (`i`) loop has corrupted the outer repeat item (which is clear as there is a single dict).

Due to macros, a template writer may not know which nested repeat names are used. It may therefore be difficult to avoid the problem.

`zope.pagetemplate` uses a `MultiMapping` (essentially a stack of `dict`s) to avoid this problem. When a scope is entered, a new empty `dict` is pushed; when a scope is exited, the `dict` is popped.

**Comment by dataflake** [comment] 2021-02-19 15:22
This is a duplicate of #177

**Closed by dataflake** 2021-02-19 15:22 UTC
Labels: core, duplicate
