### ISSUE TITLE
Python 3.9: Creating invalid Python code

### ISSUE THREAD

**Issue by icemac** [malthe/chameleon#319] opened 2020-06-30 08:07 UTC
This following snipped of generated Chameleon code is taken from the Zope tests which fail on Python 3.9 because of generated invalid syntax:

```python

            # <Substitution "y/z | python:'||'[:0]" (15:27)> -> __attr_name
            __token = 486
            try:
                __attr_name = _static_4444020112(getitem('y'), econtext, True, ('z', ))
            except (AttributeError, LookupError, NameError, TypeError, ValueError, _NotFound, _Unauthorized, _LocationError, ):
                __token = 492
                __attr_name = _guarded_getitem('||', :0)
```
The error is in the last line in `:0`.

In Python 3.8 the generated code is valid and looks like the following:

```python
            # <Substitution "y/z | python:'||'[:0]" (15:27)> -> __attr_name
            __token = 486
            try:
                __attr_name = _static_4561636800(getitem('y'), econtext, True, ('z', ))
            except (AttributeError, LookupError, NameError, TypeError, ValueError, _NotFound, _Unauthorized, _LocationError, ):
                __token = 492
                __attr_name = _guarded_getitem('||', get('slice', slice)(None, 0, None))
```

I was using 3.9.0b3 on MacOS but the error is also on TravisCI, see https://travis-ci.org/github/zopefoundation/Zope/jobs/703426836

**Comment by malthe** [comment] 2020-06-30 11:54
That's weird-looking...

**Comment by dataflake** [comment] 2020-06-30 12:21
Could this be the result of this change in RestrictedPython? https://github.com/zopefoundation/RestrictedPython/commit/483353854f1e4b90f645f7fa1dc3352379a3f995

**Comment by icemac** [comment] 2020-07-01 06:26
> Could this be the result of this change in RestrictedPython? [zopefoundation/RestrictedPython@4833538](https://github.com/zopefoundation/RestrictedPython/commit/483353854f1e4b90f645f7fa1dc3352379a3f995)

@d-maurer Do you think that @dataflake is right about that change causing this issue?

**Comment by d-maurer** [comment] 2020-07-01 07:34
Michael Howitz wrote at 2020-6-30 23:26 -0700:
>> Could this be the result of this change in RestrictedPython? [zopefoundation/RestrictedPython@4833538](https://github.com/zopefoundation/RestrictedPython/commit/483353854f1e4b90f645f7fa1dc3352379a3f995)
>
>@d-maurer Do you think that @dataflake is right about that change causing this issue?

I do not think that the respective commit can cause invalid syntax
in Python 3.9 (at least not unless the current 3.9.x behaves very
differently from 3.9a5).

Python 3.9 (at least 3.9a5) has drastically simplified "subscription"
handling. Formerly, special "ast" classes were used
to describe the subscript - special `slice` wrapping was necessary
in many cases when such a subscription was transformed into a
"guarded_getitem" function call.
Now, most subscripts are described by "ast.expr" and those
can be directly used in function calls.
The commit simply takes care of this change.


`chameleon` generates code on the "ast" level.
It is therefore sensible for abstract syntax changes
(like the above changed subscription handling).
I suppose the problem there rather than in `RestrictedPython`.
While `RestrictedPython`, too, operates on the abstract
syntax trees (and therefore,too, is sensible with respect
to changes), it typically only rearranges (or checks) them.
This is less prone to incompatibilities then the initial
"ast" generation (done by `chameleon`).

**Comment by d-maurer** [comment] 2020-07-01 12:37
Michael Howitz wrote at 2020-6-30 23:26 -0700:
>> Could this be the result of this change in RestrictedPython? [zopefoundation/RestrictedPython@4833538](https://github.com/zopefoundation/RestrictedPython/commit/483353854f1e4b90f645f7fa1dc3352379a3f995)
>
>@d-maurer Do you think that @dataflake is right about that change causing this issue?

The problem is understood:
while `chameleon` constructs the code on `ast` level,
it does not generates byte code from the constructed `ast` tree
but `unparse` it (to obtain Python source code) and then compile
this into byte code.
While with Python 3.9, `ast.Slice` is a subclass of `ast.expr`
(and therefore can be used whereever an expression is allowed),
its `unparse` representation is invalid at the Python source code
level.

This is demontrated by the following transscript:
```
>>> from ast import *
>>> ...
>>> print(dump(fc, indent=4))
Module(
    body=[
        Assign(
            targets=[
                Name(id='x', ctx=Store())],
            value=Call(
                func=Name(id='f', ctx=Load()),
                args=[
                    Slice(
                        upper=Constant(value=0))],
                keywords=[]))],
    type_ignores=[])
>>> co = compile(fc, "<string>", "exec")
>>> def f(x): return x
...
>>> exec(co)
>>> x
slice(None, 0, None)
>>> print(unparse(fc))

x = f(:0)
```
This shows: the `ast` `fc` can be compiled and executed without problems
but the result of `unparse(fc)` gives invalid Python source code.


There are many ways to address this problem:

 * one could argue that the problem is caused by `ast.unparse`:
   it returns invalid Python source code for a valid `ast` tree.

   But `fc` above was not created by a direct `ast.parse`. Instead,
   it is the result of a transformation - and `unparse` may
   claim only to produce a syntactically correct source code only
   for trees which were directly created from such source code

 * one could argue that `chameleon` is to blame: it `unparse`s
   the `ast` tree into Python source code - thus introducing unnecessary
   restrictions.

   This detour via Python source code should not
   really be necessary and should easily be avoidable

 * one could argue that `RestrictedPython` is to blame
   because it performs `ast` transformations leading
   to trees without (simple) valid Python source representation.

Personally, I would address the issue in `chameleon`:
I see no real need for the intermediate transformation into
Python source code.

**Comment by malthe** [comment] 2020-07-01 16:29
I'm not sure how to reproduce this issue in Chameleon (as a test case).

**Comment by d-maurer** [comment] 2020-07-01 17:15
Malthe Borch wrote at 2020-7-1 09:29 -0700:
>I'm not sure how to reproduce this issue in Chameleon (as a test case).

The issue arises through an interaction between `chameleon`
and `RestrictedPython`. Thus, in order to reproduce the problem,
both need to be integrated. You cannot reproduce it with `chameleon`
alone.

The problematic expression is "path:x/y | python: ''[:0]"
where "x/y" results in an error. `chameleon` roughly generates code
of the form

   try: __value = <evaluate "path:x/y">
   except ...:
     __value = ""[:0]

A `RestrictedPython` transformation turns
`""[:0]` into `_guarded_getitem_("", :0, ...)`. The latter
expression is valid on the `ast` level
(because the `ast.Slice` representing `:0` is an
instance of `ast.expr`) but not on the source code level (where
`:0` is valid only as part of a subscript).

**Comment by malthe** [comment] 2020-07-02 09:48
@d-maurer I have created an attempt at fixing this; not sure if it works for you as-is, but it should be a good starting point nonetheless.

**Comment by dataflake** [comment] 2020-07-02 11:55
I can confirm that all tests on Zope `master` under Python 3.9 with RestrcitedPython `master` and this Chameleon branch now run through without error.

**Comment by icemac** [comment] 2020-07-03 13:06
Thank you all for looking into and fixing this issue.
Should I close it?

**Comment by malthe** [comment] 2020-07-03 14:57
Yeah let's close it.

**Closed by malthe** 2020-07-03 14:57 UTC
Labels: core
